// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using prisonbreak.Server.Data;

#nullable disable

namespace prisonbreak.Server.Migrations
{
    [DbContext(typeof(HashiDbContext))]
    partial class HashiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("prisonbreak.Server.Models.Bridge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Direction")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FromIslandId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDouble")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PuzzleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ToIslandId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FromIslandId");

                    b.HasIndex("PuzzleId");

                    b.HasIndex("ToIslandId");

                    b.ToTable("Bridges", (string)null);
                });

            modelBuilder.Entity("prisonbreak.Server.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ElapsedSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HintsUsed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlayerBridgesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PuzzleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Score")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("SessionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PuzzleId");

                    b.HasIndex("SessionId");

                    b.ToTable("Games", (string)null);
                });

            modelBuilder.Entity("prisonbreak.Server.Models.Island", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PuzzleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RequiredBridges")
                        .HasColumnType("INTEGER");

                    b.Property<int>("X")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Y")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PuzzleId");

                    b.ToTable("Islands", (string)null);
                });

            modelBuilder.Entity("prisonbreak.Server.Models.Puzzle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Difficulty")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Difficulty");

                    b.ToTable("Puzzles", (string)null);
                });

            modelBuilder.Entity("prisonbreak.Server.Models.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("LastActivityAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionToken")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserAgent")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SessionToken")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Sessions", (string)null);
                });

            modelBuilder.Entity("prisonbreak.Server.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("prisonbreak.Server.Models.Bridge", b =>
                {
                    b.HasOne("prisonbreak.Server.Models.Island", "FromIsland")
                        .WithMany("BridgesFrom")
                        .HasForeignKey("FromIslandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("prisonbreak.Server.Models.Puzzle", "Puzzle")
                        .WithMany("SolutionBridges")
                        .HasForeignKey("PuzzleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("prisonbreak.Server.Models.Island", "ToIsland")
                        .WithMany("BridgesTo")
                        .HasForeignKey("ToIslandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromIsland");

                    b.Navigation("Puzzle");

                    b.Navigation("ToIsland");
                });

            modelBuilder.Entity("prisonbreak.Server.Models.Game", b =>
                {
                    b.HasOne("prisonbreak.Server.Models.Puzzle", "Puzzle")
                        .WithMany("Games")
                        .HasForeignKey("PuzzleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("prisonbreak.Server.Models.Session", "Session")
                        .WithMany("Games")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Puzzle");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("prisonbreak.Server.Models.Island", b =>
                {
                    b.HasOne("prisonbreak.Server.Models.Puzzle", "Puzzle")
                        .WithMany("Islands")
                        .HasForeignKey("PuzzleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Puzzle");
                });

            modelBuilder.Entity("prisonbreak.Server.Models.Session", b =>
                {
                    b.HasOne("prisonbreak.Server.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("prisonbreak.Server.Models.Island", b =>
                {
                    b.Navigation("BridgesFrom");

                    b.Navigation("BridgesTo");
                });

            modelBuilder.Entity("prisonbreak.Server.Models.Puzzle", b =>
                {
                    b.Navigation("Games");

                    b.Navigation("Islands");

                    b.Navigation("SolutionBridges");
                });

            modelBuilder.Entity("prisonbreak.Server.Models.Session", b =>
                {
                    b.Navigation("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
